version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: addok
      POSTGRES_USER: addok
      POSTGRES_PASSWORD: addok
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "6379:6379"
